### ISSUE TITLE
Proposal:  Make IORING_OP_* consts public

### ISSUE THREAD

**Issue by twissel** [withoutboats/iou#12]
Currently ```SubmissionQueueEvent::raw_mut``` declared as public, it would be useful to make those constants public too

**Comment by withoutboats** [comment]
I think this makes some but probably they should be exposed in `uring-sys` instead of here. (And we should be using consts from `uring-sys` in `iou` instead of defining them in `src/sqe.rs`).

**Comment by twissel** [comment]
Yes, I agree

**Comment by twissel** [comment]
And once again, If you don't mind I can submit a pull request :)

**Comment by withoutboats** [comment]
Please do :)
