### ISSUE TITLE
Stop using ptr casts so much

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/iou#2]
Unfortunately I am an old Rustacean and I write bad code, so I get the address of a slice by writing:

```rust
let addr  = slice as *const [_] as *const () as usize;
```

or the moral equivalent. When what I should write is:

```rust
let addr = slice.as_ptr() as usize;
```

This latter way is easier to review, clearer, and more solid in the face or refactors.

**Comment by Hippolot** [comment]
I can take this issue. OK?

**Comment by withoutboats** [comment]
Thanks for fixing this!
