### ISSUE TITLE
Question: why we have Sync impl on CompletionQueue, SubmissionQueue?

### ISSUE THREAD

**Issue by twissel** [withoutboats/iou#23]
See: https://github.com/axboe/liburing/issues/11#issuecomment-533894530

**Comment by withoutboats** [comment]
This is safe because Sync only means that immutable shared references can be sent across threads. Every method that mutates the queues takes a mutable reference, `&mut self`, guaranteeing that whoever calls it has synchronized, exclusive access to that queue.

**Comment by twissel** [comment]
Yes, just realized that, sorry

**Comment by withoutboats** [comment]
No worries :)
